### PR TITLE
Refactor input and fix many bugs

### LINKED ISSUE #4: Can't enter game on Chrome-based browsers
In case you didn't already fix it: disabling a submit button in a form when click leads to undefined behaviour. In Firefox, the form is submitted before the button is disabled. In Chrome, the button is first disabled and thus the form is not / cannot be submitted.

The suggested fix is to instead disable all submit buttons when the form is submitted, rather than when the button is clicked. This will ensure that the form is submitted on all browsers, after which you to disable the buttons as an indicator that the form has been submitted and something is happening.

### PR DESCRIPTION
**Pull request by teonistor**

### CODE REVIEW

File: src/main/java/io/github/teonistor/chess/core/Game.java [hunk 1]
```diff
@@ -36,8 +36,9 @@ public GameCondition getCondition() {
     public void triggerView(final View view) {
         switch (getCondition()) {
```
Comment (rhys-saldanha) [inline src/main/java/io/github/teonistor/chess/core/Game.java:37]: oh no a `switch` statement!

File: src/main/resources/static/chess/front.html [hunk 2]
```diff
@@ -14,9 +15,9 @@ <h4>Choose player:</h4>
     <form v-for="player in players"
           :key="player"
           :action="'/chess-api/assign-' + player.toLowerCase()"
+          @submit="clicked=player"
```
Comment (rhys-saldanha) [inline src/main/resources/static/chess/front.html:18]: perfect

**Review by rhys-saldanha — APPROVED** [review]
